apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend  # This should match the label of your frontend Pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
